version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   expose: 
  #     - 8000
  #   volumes:
  #     - ./django_app:/app
  #   command: sh -c "python manage.py runserver 0.0.0.0:8000"
  #   depends_on:
  #     - db
  #     - kafka
  #     - rabbitmq
    
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./sql_data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_DB: ${PGDB}
      POSTGRES_PASSWORD: ${PGPWD}

  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - "9092:9092"
    expose:
      - "9092"
    hostname: kafka
    links: 
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  rabbitmq:
    image: 'rabbitmq'
    environment:
        - RABBITMQ_USERNAME=rabbitmq
        - RABBITMQ_PASSWORD=rabbitmq
    ports:
        - '5672:5672'
        - '15672:15672'