# Generated by Django 3.1 on 2020-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Datetime')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('traffic_mb', models.IntegerField(default=0, verbose_name='traffic')),
            ],
            options={
                'verbose_name': 'Traffic entry',
            },
        ),
    ]
