# Generated by Django 3.1 on 2020-08-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200824_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlog',
            old_name='user_id',
            new_name='user',
        ),
    ]
